
development:
  adapter: mysql2
  database: rideshare
  username: root
  password: 

test:
  adapter: mysql2
  database: rideshare-test
  username: root
  password: 


production:
  adapter: mysql2
  database: rideshare
  username: root
  password: 
