common: &common 
  adapter: mysql2
  username: root
  password:

development: 
  <<: *common
  database: cru_dev
  
test:
  <<: *common
  database: cru_test

production:
  <<: *common
  database: cru_prod
