# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development: &common
  adapter: mysql2
  database: prod
  username: root
  password: newlife

test:
  <<: *common
  database: test-prod

production:
  <<: *common
